### ISSUE TITLE
Temperature could not read from data/temp.txt

### ISSUE THREAD

**Issue by dndam** [dndam/mea-domus#15]
If you start the application from a different location (e.g. as a cron) the temperature txt file is not found

# /home/pi/github/mea-domus/bin/console boiler

Temperature could not read from data/temp.txtTemperature could not read from data/temp.txtTemperature could not read from data/temp.txt^C

**Comment by abogdan** [comment]
This has already been fixed in 9a7e518ca3d7e1d0b83714f3cc19e6877c8829a3
